### ISSUE TITLE
ResourcesBot: Implement proper module registration

### ISSUE THREAD

**Issue by holybiber** [4training/pywikitools#113]
We now have a couple of modules (= post-processors) doing helpful stuff with the data gathered in the first step. (Hint: use `--read-from-cache` to skip the lengthy querying of all worksheets and directly read from the results)

However the `run()` function in [bot.py](pywikitools/resourcesbot/bot.py) looks rather ugly because it has separate lines for each module.

Move all modules into a subfolder `modules/` and implement some easy functionality to load them. Doesn't need to be fancy reflection stuff (scan directory `modules/` and read all python files from there...), it's better to keep it simple and have something like
```
load_module('consistency')
load_module(...)
```
Then have a `--modules` command line option where it's possible to select the modules I want to run. It would be great if several modules can be specified (comma-separated). However I just realize that this is a bit tricky as `parse_arguments()` already needs to know which modules are available... Maybe register the modules already there and then pass the modules that should be run in the constructor to `ResourcesBot`?

ResourcesBot should log (loglevel info) which modules it's going to run.

**Comment by holybiber** [comment]
Let's have a static list in `resourcesbot.py`:
```
AVAILABLE_MODULES = [
        'consistency_check',
        'export_html',
        'export_pdf',
        'export_repository',
        'write_lists',
        'write_report',
        'write_sidebar'
    ]
```
and then unify the constructors of all LanguagePostProcessors to match this one:
```
class LanguagePostProcessor(ABC):
    @abstractmethod
    def __init__(self, config: ConfigParser, fortraininglib: ForTrainingLib, site: pywikibot.site.APISite, *,
                 force_rewrite: bool = False) -> None:
        pass
```
Now there is no need to have all these lengthy instantiations of `WriteList`, `WriteReport` etc.
Instead, load them dynamically, similar to how we load correctors in `CorrectBot` (see `_load_corrector()` in [correctbot/bot.py](/4training/pywikitools/blob/main/pywikitools/correctbot/bot.py))

Also introduce an optional argument modules into the constructor of `ResourcesBot`:
```
def __init__(self, config: ConfigParser, limit_to_lang: Optional[str] = None, modules: list[str] = AVAILABLE_MODULES, rewrite: Optional[str] = None,
                 read_from_cache: bool = False):
```
in `resourcesbot.py` the choices for the command line argument can be taken directly from `AVAILABLE_MODULES`

**Comment by holybiber** [comment]
After looking at #114 I changed my mind: Let's have this property and the help summary text in the module classes and read from them for the command line options.
Like changing the ABC to
```
class LanguagePostProcessor(ABC):

    @property
    @abstractmethod
    def can_be_rewritten(self) -> bool:
        """Is the force_rewrite flag available for this module?"""
        raise NotImplementedError

    @property
    @abstractmethod
    def help_summary(self) -> str:
        """Used for the resourcesbot.py -h help command"""
        raise NotImplementedError
```
and then any of the modules can just start like this:
```
class WriteList(LanguagePostProcessor):
    can_be_rewritten = True
    help_summary = "Write list of available training resources into mediawiki"
```

Implementing this should be just a few lines if we make the `load_module(str)` function a public function at module level in `resourcesbot/bot.py`.
Then in `resourcesbot.py` we can go through all AVAILABLE_MODULES, load the corresponding classes and read these properties to feed the information to the argument parser.

**Comment by GabrielSousa02** [comment]
One question I have is:

By writing the following code:

```python
# post_processing.py

class LanguagePostProcessor(ABC):

    @property
    @abstractmethod
    def can_be_rewritten(self) -> bool:
        """Is the force_rewrite flag available for this module?"""
        raise NotImplementedError

###########################

# modules/write_lists.py

class WriteList(LanguagePostProcessor):
    can_be_rewritten = True
    help_summary = "Write list of available training resources into mediawiki"
```

Talking specifically about the `can_be_rewritten` property, we would force, upon class definition, that the `force_rewrite` option would be default `True` (for the classes that have that option), and we would not be able to run it without rewriting everything, correct? 

If my logic is right, is this something we want to enforce?

Another two things that occurred me:
1 - We would still need to implement that at the constructor level, so it means we would need to have specific class builders at the parsing of the script.

2 - At this point, I'm going through the path of using the `ABC` class to standardize the builders, while not enforcing optional fields, and making the `LanguagePostProcessor` generalist, while it's children will have the specificity of each implementation. Down this path, I don't see the need of a `load_modules` function, since we can map all the langue processors modules into a dict, and then pass use the standardized builder, and let each module do what is meant to do. then call the `run()` method. See below

```python
# post_processing.py
class LanguagePostProcessor(ABC):
    """Base class for all functionality doing useful stuff with the data on one language.

    We include information on English as well because several post-processors need it as reference
    """

    def __init__(
        self,
        fortraininglib: ForTrainingLib,
        config: ConfigParser = None,
        site: pywikibot.site.APISite = None,
        *,
        force_rewrite: bool = False,
):
        self.fortraininglib = fortraininglib
        self._config = config
        self._site = site
        self._force_rewrite: Final[bool] = force_rewrite


    @abstractmethod
    def run(self, language_info: LanguageInfo, english_info: LanguageInfo,
            changes: ChangeLog, english_changes: ChangeLog):
        """Entry point"""
        raise NotImplementedError()
```

`WriteList` is looking like:

```python
class WriteList(LanguagePostProcessor):
    """
    Write/update the list of available training resources for languages.

    We only show worksheets that have a PDF file (to ensure good quality)

    This class can be re-used to call run() several times
    """

    def __init__(
        self,
        fortraininglib: ForTrainingLib,
        config: ConfigParser,
        site: pywikibot.site.APISite,
        *,
        force_rewrite: bool = False,
    ):
        """
        Arguments user_name and password are necessary to mark page for translation
        in case of changes.
        In case they're empty we won't try to mark pages for translation
        Args:
            force_rewrite rewrite even if there were no (relevant) changes
        """
        super().__init__(fortraininglib, config, site, force_rewrite=force_rewrite)

        self._user_name: Final[str] = config.get(
            "resourcesbot", "username", fallback=""
        )
        self._password: Final[str] = config.get("resourcesbot", "password", fallback="")
        self.logger: Final[logging.Logger] = logging.getLogger(
            "pywikitools.resourcesbot.modules.write_lists"
        )

        if self._user_name == "" or self._password == "":
            self.logger.warning(
                "Missing user name and/or password in config."
                "Won't mark pages for translation."
            )
``` 

Any comments? Is it making sense?

**Comment by GabrielSousa02** [comment]
Ok! I will look into that when I finish the first portion of the refactoring!
