### ISSUE TITLE
ResourcesBot: Get force_rewrite from module definition

### ISSUE THREAD

**Issue by holybiber** [4training/pywikitools#114]
Currently the `force_rewrite` (command line arg `--rewrite`) is hard-coded which is suboptimal.

Implement a way to store this information in the module definition (connected to #113) so it's loaded automatically whether a module has a force_rewrite option (not all modules have it, the constistency checks e.g. don't have it currently as they're writing to the console only)

**Comment by GabrielSousa02** [comment]
@holybiber based on the implementation of the #113, do you think we solved this issue?

**Comment by holybiber** [comment]
Yes that's done, closing it
