### ISSUE TITLE
Implement test framework basics

### ISSUE THREAD

**Issue by holybiber** [4training/pywikitools#29]
Have base class `CorrectTest(unittest.TestCase)` that all language-specific tests will be based on.

Needs to take language code of the language we're testing in constructor (to avoid redundancy of having to define that in every line again).

Have essential function to check whether given input produces expected output (one-line function call)

**Comment by DoubleTheP** [comment]
Not needed anymore. 

Due to rework in https://github.com/4training/pywikitools/issues/26, a simple class suffices
