### ISSUE TITLE
Implement test function for checking against revisions on the server

### ISSUE THREAD

**Issue by holybiber** [4training/pywikitools#30]
Based on basic function call (see #19 ): Have an older revision of one translation unit as the input and check whether the output of our corrector is identical to the newer revision of it. 
Takes three arguments:
- name of translation unit
- old revision ID
- new revision ID

This is similar to checking
https://www.4training.net/mediawiki/index.php?title=Translations:How_to_Continue_After_a_Prayer_Time/1/ar&type=revision&diff=62258&oldid=62195

**Comment by DoubleTheP** [comment]
Use to-be-then-provided function from `fortraininglib.py` to access an old revision of a translation unit, pipe it through the corrector, and diff it against the new revision. If the output is the same, the test succeeded, if not, the test failed.

**Comment by DoubleTheP** [comment]
typo: the method that changed is not called `get_translation_unit()` but `get_translated_unit`

**Comment by DoubleTheP** [comment]
`name of translation` means `{page}/{identifier}/{language_code}`
