### ISSUE TITLE
Add method for retrieving specific revision of a page

### ISSUE THREAD

**Issue by holybiber** [4training/pywikitools#33]
Either extent fortraininglib.get_page_source() or make a new one.
This is necessary for #30 

This is the API call for retrieving revision id 671 of translation unit Translations:Prayer/1/de
https://www.4training.net/mediawiki/api.php?action=query&prop=revisions&rvstartid=671&rvlimit=1&rvprop=content&format=json&titles=Translations:Prayer/1/de

Bonus: This gives a warning (as well as the current implementation of get_page_source()) because of a missing rvslots property. Research this and probably add rvslots=* into our call

**Comment by holybiber** [comment]
`get_page_source()` and `get_translation_unit()` now take optional parameter `revision_id`.

Besides we now set rvslots=main as we want to access the main slot.

**Comment by DoubleTheP** [comment]
> `get_page_source()` and `get_translation_unit()` now take optional parameter `revision_id`.
> 
> Besides we now set rvslots=main as we want to access the main slot.

typo: the method that got changed is not called `get_translation_unit()`, but `get_translated_unit` instead
