### ISSUE TITLE
Resourcesbot: Print reports

### ISSUE THREAD

**Issue by holybiber** [4training/pywikitools#8]
For each language: how many worksheets are translated? How many of them have PDF files (and which)?
Where did we find incomplete translations?
And combining all these into an overall report

**Comment by JosuaKugler** [comment]
In order to check for incomplete translations it seems necessary to loop through all translation units, yielding a huge number of API calls. This appears to be very inefficient.
Jan and I would suggest downloading the whole information for a given worksheet and language and then check for incomplete translations locally.

**Comment by JosuaKugler** [comment]
In `process_page` only the "Page Display Title" and the downloadable files translation units are processed.
We don't understand why just those were chosen?

**Comment by holybiber** [comment]
> In order to check for incomplete translations it seems necessary to loop through all translation units, yielding a huge number of API calls. This appears to be very inefficient.
Looping through individual translation units is not necessary, we just need what is done in `list_page_translations()` in fortraininglib.py - it is calling e.g. https://www.4training.net/mediawiki/api.php?action=query&meta=messagegroupstats&mgsgroup=page-Church
We need some refactoring of `list_page_translations()` because the information on incomplete translations currently stays within the library call but we need it in resourcesbot to generate reports.

**Comment by holybiber** [comment]
> In `process_page` only the "Page Display Title" and the downloadable files translation units are processed.
> We don't understand why just those were chosen?

The main purpose of the script is to fill out the "available resources in ..." section in the language information pages, e.g. https://www.4training.net/German#Available_training_resources_in_German
There we only need the worksheet title and the names of the downloadable files, that's why we only look at them and don't have to process any of the actual content of worksheets.

**Comment by holybiber** [comment]
Thanks! There is still two issues with this:
1) The section "PDF missing" in individual reports is incorrect, it lists all other worksheets, also where there is actually nothing translated yet
2) total_summary() should only be called if the --lang option isn't set
